### PR TITLE
Ionic Datepicker

### PR DESCRIPTION
**Pull request by olivercodes**
#### About

Author List:
@olivercodes 
@Teresa101 

Together, we'd like to propose a new Date Picker for the Ionic Framework. It's being written in Stencil so that efforts to get it working in React, Angular, and Vue are minimal. 

Heavily inspired by https://vuetifyjs.com/en/components/date-pickers

#### Short description of what this resolves:
- Lack of a date picker in Ionic

#### Changes proposed in this pull request:

- Adds a Date Picker to Ionic
- Adds a Date Picker Form Input to Ionic
- Adds a Date Picker Popover 

**Ionic Version**:
4

### Changelog of Progress

- [x] @olivercodes committed initial day picker scaffold and month tabbing logic
- [x] @Teresa101 committed initial daypicker css

### Current Demo (we'll keep this updated as we progress)

Kapture 2019-03-24 at 15 08 50
(Gif created with https://github.com/wulkano/kap)

### CODE REVIEW

**Comment by Teresa101** [comment]
@olivercodes Please re-check the changes I made. Thanks.

**Comment by olivercodes** [comment]
@Teresa101 Thanks for the first commit! Looking good!

**Comment by olivercodes** [comment]
@Teresa101  I noticed that in desktop mode the top buttons are getting this weird box outline: 
image

**Comment by olivercodes** [comment]
@brandyscarney @mhartington - tagging you early to get initial reactions

**Comment by Teresa101** [comment]
@olivercodes I just updated style rules for buttons to get rid of the background and border.

**Comment by olivercodes** [comment]
@teresa101 next step is we add the select for day value. I’ll add this function tonight, and push up. When that’s ready, I’ll need the button selected css, some kind of little round circle on the day value when you open the picker that already has a selected value.

**Pull request closed without merging**
